PROGRAM TESTGRID
IMPLICIT NONE
REAL(KIND = 8), PARAMETER :: PI = 3.141592653589790D+00
INTEGER, PARAMETER :: NI = 20, NJ = 10, NK = 1, NOUT = 1
INTEGER :: AXSYM
INTEGER :: NSTEP
INTEGER :: NBLOCK
INTEGER :: NVAR
INTEGER :: NBASEVAR2


INTEGER :: I,J,K

REAL(KIND= 8), PARAMETER :: DX = 1.0D0, DY = 1.0D0
REAL(KIND = 8) :: WERT(NI,NJ)
OPEN(100,FILE="git.dat")
WRITE(100,'(2I5)') NI+1, NJ+1
DO j = 0,NJ
   DO i= 0,NI
      WRITE(100,'(3(X,D20.13))') DX/NI * DBLE(i), DY/NJ * DBLE(j), 1.0D0
   END DO
END DO
CLOSE(100)

DO j = 1,NJ
   DO i= 1,NI
!      WERT(i*j) = DBLE(i*j)
       WERT(i,j) = SIN(DBLE(i-1)*PI/DBLE(NI-1))*COS(DBLE(J-1)*PI/DBLE(NJ-1))
!       WERT(i,j) = SIN(DBLE(i-1)*PI/DBLE(NI-1))!*COS(DBLE(J-1)*PI/DBLE(NJ-1))
   END DO
END DO

AXSYM=0
NSTEP=0
NBLOCK=1
NVAR=1
NBASEVAR2=1
OPEN(100,FILE="avarout.ufo",FORM="UNFORMATTED")
WRITE(100) AXSYM,NSTEP,NBLOCK,NVAR,NBASEVAR2
WRITE(100) NI,NJ,NK
WRITE(100) NOUT,NOUT,NOUT
WRITE(100) "TESTVAR             "
WRITE(100) (((WERT(i,j),i=1,NI),j=1,NJ),k=1,1)

CLOSE(100)

END PROGRAM
