program gridgen_o_grid
implicit none
INTEGER, PARAMETER :: NB = 1
INTEGER, PARAMETER :: AXSYM = 1
INTEGER, PARAMETER :: NI = 10
INTEGER, PARAMETER :: NJ = 12
INTEGER, PARAMETER :: FU = 666

INTEGER :: I ,J
WRITE(*,*) "GRIDGEN FÜR EIN EINFACHES SCHRÄGES GITTER 10.10.2014"

OPEN(FU,FILE="git.bin",FORM="UNFORMATTED",access="STREAM",STATUS="replace")

WRITE(FU) AXSYM,NB
!!! BLOCK 1.
WRITE(FU) NI+1,NJ+1

DO J = 0, NJ
   DO I = 0,NI
      WRITE(FU) DBLE(I)*(0.5D0+DBLE(NJ-J)/DBLE(NJ*2)),DBLE(J)
   END DO
END DO


CLOSE (FU)
WRITE(*,*) "DONE"


end program
