SUBROUTINE CALC_SCHIEBESPANNUNG()
   USE MOD_GLOBAL
   USE CONST
   use wall_refinement, only: calc_wall_refinement
   implicit none

   UNSTR%KNT_SPANNUNG = 1.0D-5

!   CALL CALC_1_ORDER_GRADIENT(1)
   CALL ELLIPTIC_GRID_SMOOTHNING()

   IF (GLOBAL % DO_WALL_REFINEMENT >= 1) THEN
!      CALL WANDVERFEINERUNG()
      call calc_wall_refinement()
   END IF

END SUBROUTINE


SUBROUTINE ELLIPTIC_GRID_SMOOTHNING()
   USE MOD_GLOBAL
   IMPLICIT NONE

   INTEGER :: U,P1,P2

#ifdef DEBUG
   IF (GLOBAL%DBG >= 1)  THEN
      WRITE(*,'(A)') "GRID_SMOOTHING"
   END IF
#endif

   IF (GLOBAL % AXSYM == 2) THEN
      WRITE(*,*) "3D NOCH NICHT UNTERSTÜTZT","ELLIPTIC_GRID_SMOOTHNING"
      STOP
   END IF

   DO U = 1, UNSTR % NKNT
      P1 = UNSTR % KNT(U,1)
      P2 = UNSTR % KNT(U,2)
      UNSTR % KNT_SPANNUNG(U,1) = 1.0D0 * ABS( UNSTR % KNT_DN(U,1) )
   END DO

END SUBROUTINE

   SUBROUTINE CELL_INC()
   !< DIESE ROUTINE SORGT FÜR NICHT ZU GROßE ASPECT RATIOS ZWEITER KANTEN
   USE MOD_GLOBAL
   IMPLICIT NONE

   INTEGER :: U,P1,P2

   REAL(KIND=8) :: TEMP

#ifdef DEBUG
   IF (GLOBAL%DBG >= 1)  THEN
      WRITE(*,'(A)') "CELL_INC"
   END IF
#endif

   IF (GLOBAL % AXSYM == 2) THEN
      WRITE(*,*) "3D NOCH NICHT UNTERSTÜTZT","WANDVERFEINERUNG"
      STOP
   END IF

   DO U = 1, UNSTR % NKNT
      P1 = UNSTR % KNT(U,1)
      P2 = UNSTR % KNT(U,2)
      TEMP = 0.0D0
      IF (UNSTR % PKT_TYPE (P1) == 2 .NEQV. UNSTR % PKT_TYPE (P2) == 2) THEN
         IF (UNSTR % KNT_DN(U,1) > 1.D-1) THEN
            TEMP = MIN(10.D0,(UNSTR % KNT_DN(U,1)-1.D-1) * 10)
         END IF
      END IF
      UNSTR % KNT_SPANNUNG(U,1) = UNSTR % KNT_SPANNUNG(U,1) + ABS(TEMP)! * UNSTR % KNT_DN(U,N+1))
   END DO
   END SUBROUTINE

