module debug
implicit none
private
   INTEGER, PARAMETER       :: GRID_COMMENTS = 1
   INTEGER, PARAMETER       :: GRID_CONNECTIONS = 2
   INTEGER, PARAMETER       :: GRID_KANTEN = 4
   INTEGER, PARAMETER       :: GRID_VERSCHIEB = 8

   LOGICAL, PUBLIC, SAVE    :: DBG_GRID_COMMENTS = .FALSE.
   LOGICAL, PUBLIC, SAVE    :: DBG_GRID_CONNECTIONS = .FALSE.
   LOGICAL, PUBLIC, SAVE    :: DBG_GRID_KANTEN = .FALSE.
   LOGICAL, PUBLIC, SAVE    :: DBG_GRID_VERSCHIEB = .FALSE.

   public init_debug_levels
contains
subroutine init_debug_levels
use mod_global, only: global
implicit none
IF (MOD(GLOBAL%DBG,2*GRID_COMMENTS) >= GRID_COMMENTS) then
   DBG_GRID_COMMENTS = .TRUE.
   WRITE(*,*) "DEBUG: WRITING GRID COMMENTS"
end if
IF (MOD(GLOBAL%DBG,2*GRID_CONNECTIONS) >= GRID_CONNECTIONS) then
   DBG_GRID_CONNECTIONS = .TRUE.
   WRITE(*,*) "DEBUG: WRITING GRID BLOCK CONNECTION"
end if
IF (MOD(GLOBAL%DBG,2*GRID_KANTEN) >= GRID_KANTEN) then
   DBG_GRID_KANTEN = .TRUE.
   WRITE(*,*) "DEBUG: WRITING GRID EDGE CONNECTION"
end if
IF (MOD(GLOBAL%DBG,2*GRID_VERSCHIEB) >= GRID_VERSCHIEB) then
   DBG_GRID_VERSCHIEB = .TRUE.
   WRITE(*,*) "DEBUG: WRITING GRID MOVEMENT TESTS"
end if

end subroutine

end module debug
