MODULE TYPES
   TYPE :: TGLOBAL
      INTEGER :: AXSYM
      INTEGER :: NSTEP
      INTEGER :: NBLOCK
      INTEGER :: NVAR
      INTEGER :: NBASEVAR2
      INTEGER :: DBG
!< DEBUGING LEVEL
      INTEGER :: NITER
      INTEGER :: FILE_TYPE
!< ART DER INPUTDATEIEN:
!<  0: OLD ASCII
!<  1: NEW MPIIO FILE TYPES
      INTEGER :: OUTPUT_TYPE
!< ART DER AUSGABEDATEIEN
!<  0: PARAVIEW
!<  1: TECPLOT
      INTEGER :: OUTPUT_ANIMATION
!< OUTPUT ANIMATION
!<  0: NO ANIMATION OUTPUT
!<  1: ANIMATION OUTPUT
      INTEGER :: CHECK_FOR_DOUBLE_POINTS
!< GIBT AN OB BEI DER ERSTELLUNG DES UNSTRUKTUIERTEN
!< GITTERS EINE ÜBERPRÜFUNG DES GITTER DURCHGEFÜHRT WERDEN SOLL
!< DABEI WERDEN ALLE PUNKTKOORINATEN MITEINANDER VERGLICHEN
!< UM ETWAIGE NICHTBEACHTUNG VON CONNECTIONS ZU ÜBERPRÜFEN
      INTEGER :: CHECK_FOR_DOUBLE_KANTEN
!< GIBT AN OB BEI DER ERSTELLUNG DES UNSTRUKTUIERTEN
!< GITTERS EINE ÜBERPRÜFUNG DES GITTER DURCHGEFÜHRT WERDEN SOLL
!< DABEI WERDEN FÜR JEDEN PUNKT ALLE KANTEN MITEINANDER VERGLICHEN
!< UM ETWAIGE NICHTBEACHTUNG VON CONNECTIONS ZU ÜBERPRÜFEN
      INTEGER :: NODE_MOVEMENT = 2
!< ART WIE DIE KNOTEN BEWEGT WERDEN SOLLEN:
!< 1: Sogennantes EQUILIBRIUM, Kanten ziehen von anderem Knoten aus
!< 2: KINEMATISCHE LÖSUNG, Kanten werden als Reine Kräfte interpretiert
      INTEGER :: DO_WALL_REFINEMENT
!< GIBT AN OB WANDVERFEINERUNG DURCHGEFÜHRt WERDEN SOLL
!< WÄNDE MÜSSEN DANN SEPERAT DEFINIERT WERDEN
      CHARACTER(LEN=100) :: RANDBED_IN
!< DATEI IN WELCHER DIE RANDBEDINGUNGEN DEFINIERT SIND
!< (IN ANLEHNUNG AN rabe.dat)
      REAL(KIND=8) :: WALL_DIST
!< GLOBALER WANDABSTAND, KANN IN DER WANDDEFINITION ÜERSCHRIEBEN WERDEN
      REAL(KIND=8) :: WEIGHT = 1/10.0D0

      REAL(KIND=8) :: FAKTOR
      CHARACTER(LEN=100) :: GIT_IN
      CHARACTER(LEN=100) :: SOL_IN
      CHARACTER(LEN=100) :: GIT_OUT
      CHARACTER(LEN=100) :: SOL_OUT
      CHARACTER(LEN=20),ALLOCATABLE:: VNAME(:)
   END TYPE

   TYPE :: TBLOCKS
      INTEGER :: NCI
      INTEGER :: NCJ
      INTEGER :: NCK
      INTEGER :: NPI
      INTEGER :: NPJ
      INTEGER :: NPK
      INTEGER :: IOUT
      INTEGER :: JOUT
      INTEGER :: KOUT
      REAL(KIND=8),ALLOCATABLE :: CVAR(:,:,:,:)
!< Cell Centered Variables (I,J,K,VAR-INDEX)

      REAL(KIND=8),ALLOCATABLE :: XYZ(:,:,:,:)
!< GITTERPUNKTE -POSITION (I,J,K,COORD)
      INTEGER, ALLOCATABLE :: ASSOC(:,:,:)
!< POINTER AUF UNSTRUTURIERTEN PUNKT; der DEN GITTERPUNKT REpresentiert
      REAL(KIND=8),ALLOCATABLE :: SWP(:,:,:,:)

      INTEGER :: BLOCK_CONNECTION (6,3)
!< GIBT BLOCKVERBDINUNG DES BLOCKES AN: (FACE,VALUE)
!< FACE: 1 = W, 2 = E, 3 = S, 4 = N, 5 = B, 6 = F
!< VALUE: 1 = BLOCKNUMMER, 2= FACE DES NACHBAR_BLOCKS, 3 = PERMUTATION            ! SCHWERPUNKT
!< BLOCKNUMMER: >0: BLOCKNUMMER
!<               0: WALL
!<              -1: SYMMETRIE
!<              -2: INFLOW
!<              -3: OUTFLOW
!<              -4: SLIPWALL
!<           -1000: UNDEFINED (INITIAL VALUE)
   END TYPE

   TYPE :: TUNSTR
      INTEGER :: NPKT
      INTEGER :: NKNT

      REAL(KIND=8),ALLOCATABLE :: XYZ(:,:)
!< KOORDINATEN DES PUNKTES
      REAL(KIND=8),ALLOCATABLE :: PKT_VAR(:,:)
!< Grid-Point Variables
      INTEGER, ALLOCATABLE :: PKT_TYPE(:)
!< Art eines Gitterpunkts:
!< 1 - normaler Grid-interner Punkt. Besitzt 4 "normale" umliegende Zellen
!< 2 - Randzelle: Kann nicht verschoben werden
!< 3 - Randzelle: Verschiebbar in X-Richtung
!< 4 - Randzellle Verschiebbar in Y-Richtung
      INTEGER, ALLOCATABLE :: PKT_NKNT(:)
!< ANzAHL DER KANTEN an PUNKTE
      INTEGER, ALLOCATABLE :: PKT_KNT(:,:)
!< KANTEN DIE IN VERBINDUNG MIT DEM PUNKT STEHEN
!< Entspricht auch der Anzahl von Nachbarn
      INTEGER, ALLOCATABLE :: PKT_NEIGH(:,:)
!< Nachbarpunkte anhand der Kanten, könnte auch über die Kanten ermittelt werden.
      INTEGER, ALLOCATABLE :: PKT_REF(:,:)
!< REFERENZKNOTENPKT AUF DEN GITTER ZUR WERTINTERPOLATION

      REAL(KIND=8),ALLOCATABLE :: DELTA(:,:,:,:,:)           ! Du/Dn an den "KANTEN" (RICHTUNG der KANTE(i,j,k), Richtungsanteil(||,x,y,z), 3xPOS
      INTEGER, ALLOCATABLE :: KNT(:,:)
!< Vorhandene Kanten = Verbindung zwischen zwei Punkten

      REAL(KIND=8),ALLOCATABLE :: KNT_DN(:,:)
!< Kantelänge 1 = Betrag, 2 = dX, 3 = dY
      REAL(KIND=8),ALLOCATABLE :: KNT_SPANNUNG(:,:)         !

!      INTEGER, ALLOCATABLE :: PKT_IS

   END TYPE
END MODULE

MODULE BOUNDARY
   implicit none
   INTEGER, ALLOCATABLE :: KNT_BOUNDARY(:)
   INTEGER              :: NKNT_BOUNDARY
   REAL(KIND = 8)       :: WALL_DIST
END MODULE

MODULE MOD_GLOBAL
   USE TYPES
   TYPE(TGLOBAL) :: GLOBAL
   TYPE(TBLOCKS), ALLOCATABLE :: BLOCKS(:)
   TYPE(TUNSTR) :: UNSTR
END MODULE

MODULE CONST
   IMPLICIT NONE
   INTEGER, PARAMETER :: DP = KIND(1.0D+0)
!   INTEGER,PARAMETER:: UML (8,3) = RESHAPE((/0,0,0,1,0,0,0,1,0,1,1,0,0,0,1,1,0,1,0,1,1,1,1,1/),(/8,3/))
INTEGER,PARAMETER:: UML (8,3) = RESHAPE((/0,1,0,1,0,1,0,1,0,0,1,1,0,0,1,1,0,0,0,0,1,1,1,1/),(/8,3/))
END MODULE
