SUBROUTINE CALC_1_ORDER_GRADIENT(VAR)
USE MOD_GLOBAL
IMPLICIT NONE

INTEGER :: VAR                                  ! NUMMER DER VARIABLE FÜR WELCHE DER GRADIENT BERECHNET WIRD

INTEGER :: N,U,P1,P2

REAL(KIND=8) :: TEMP

#ifdef DEBUG
IF (GLOBAL%DBG >= 1)  THEN
   WRITE(*,'(3A,I2.2,A)') "BERECHNE GRADIENT FÜR ",TRIM(GLOBAL%VNAME(VAR))," (VAR=",VAR,")"
   WRITE(*,'(I3)') GLOBAL%NBLOCK
END IF
#endif

IF (GLOBAL % AXSYM == 2) THEN
   WRITE(*,*) "3D NOCH NICHT UNTERSTÜTZT","CALC_1_ORDER_GRADIENT"
   STOP
END IF

DO U = 1, UNSTR % NKNT
   P1 = UNSTR % KNT(U,1)
   P2 = UNSTR % KNT(U,2)
   !UNSTR % KNT_DU(U,1,L)
   TEMP = ABS( UNSTR % PKT_VAR(P2,VAR) - UNSTR % PKT_VAR(P1,VAR) )
   TEMP = TEMP / UNSTR % KNT_DN(U,1)
   DO N = 1,2
      UNSTR % KNT_SPANNUNG(U,1) = UNSTR % KNT_SPANNUNG(U,1) + ABS(TEMP * UNSTR % KNT_DN(U,N+1))
   END DO
END DO
#ifdef DEBUG
IF (GLOBAL%DBG >= 2)  THEN
   DO U = 1, UNSTR % NKNT
      P1 = UNSTR % KNT(U,1)
      P2 = UNSTR % KNT(U,2)
      WRITE(*,'("KANTE ",I0," ZW ",I0,X,I0," WERTE ",F0.3,X,F0.3," DN ",3(F0.3,X))') &
       u,  P1,P2, UNSTR % PKT_VAR(P1,1), UNSTR % PKT_VAR(P2,1),UNSTR % KNT_SPANNUNG(U,1)
   END DO
END IF
#endif
END SUBROUTINE
