SUBROUTINE INPUT_SOL()
USE MOD_GLOBAL
USE CONST
IMPLICIT NONE
INTEGER, PARAMETER :: F_SOL = 10
INTEGER :: N
LOGICAL :: FEXISTS

IF (GLOBAL%DBG == 1) THEN
   WRITE(*,'(2A,X,A)') "OPENING ",TRIM(GLOBAL % SOL_IN)
END IF
INQUIRE(FILE=TRIM(GLOBAL% SOL_IN),EXIST=FEXISTS)
IF(FEXISTS .EQV. .FALSE.) THEN
   WRITE(*,*) "SOLUTION DATEI konnte nicht gefunden werden: " // TRIM(GLOBAL% SOL_IN)
   GLOBAL%NVAR = 1
   ALLOCATE( GLOBAL % VNAME (GLOBAL%NVAR) )
   GLOBAL % VNAME(1) = "DUMMY"
   DO N  = 1, GLOBAL % NBLOCK

      ALLOCATE( BLOCKS(N) % CVAR  (0:BLOCKS(N)%NPI,0:BLOCKS(N)%NPJ,0:BLOCKS(N)%NPK,GLOBAL%NVAR) )
      BLOCKS(N) % CVAR = 1.0D0
   END DO
ELSE
   STOP "SOLUTION MPPIO DATEI ÖFFNEN NOCH NCIHT IMPLEMENTIERT"

END IF

END SUBROUTINE
