SUBROUTINE INPUT_GRID()
USE MOD_GLOBAL
USE CONST
IMPLICIT NONE
INTEGER, PARAMETER :: GIT_UNIT = 25

LOGICAL :: FEXISTS

INTEGER :: GITDIM
INTEGER :: NUMBER_OF_CORNER_POINTS
INTEGER :: NUMBER_OF_FACES
INTEGER :: NUMBER_OF_POINTS_PER_FACE
INTEGER :: NUMBER_OF_PERMUTATIONS

REAL(KIND=8),ALLOCATABLE :: CORNER_POINT (:,:,:)

INTEGER,ALLOCATABLE :: FID2CP (:,:)
!< UMRECHNUNG VON FACE UND nter PUNKT AUF DER FACE zu CORNER PUNKT

INTEGER,ALLOCATABLE :: PERM (:,:)
!< PERMUTATION DER CORNER PUNKTE AUF ER JEWEILIGEN FACE

REAL(KIND=8),PARAMETER :: eps = 1.0D-8

INTEGER :: BB, F , FF, FP , P

LOGICAL :: FOUND

CHARACTER(LEN = 1) , PARAMETER :: FACES(6) = (/"W","E","S","N","B","F"/)

CHARACTER(LEN = 5) , PARAMETER :: FACENAME(6) = (/"WEST ","OST  ","SUED ","NORD ","BACK ","FRONT"/)

INTEGER :: B,I,J,K,V

INTEGER :: nI,nJ,nK

IF (GLOBAL%DBG == 1) THEN
   WRITE(*,'(2A,X,A)') "OPENING ",TRIM(GLOBAL % GIT_IN)
END IF
INQUIRE(FILE=TRIM(GLOBAL% GIT_IN),EXIST=FEXISTS)
IF(FEXISTS .EQV. .FALSE.) THEN
   WRITE(*,*) "GITTER INPUT DATEI konnte nicht gefunden werden: " // TRIM(GLOBAL% GIT_IN)
   STOP
END IF
OPEN(GIT_UNIT,FILE=TRIM(GLOBAL% GIT_IN),FORM="UNFORMATTED",access="STREAM",STATUS="OLD")
READ(GIT_UNIT) GLOBAL %AXSYM,GLOBAL % NBLOCK

IF (GLOBAL%DBG == 1) WRITE(*,'(2(A,X,I0,5X))') "AXSYM:",GLOBAL % AXSYM,"NUMBER_OF_BLOCKS:", GLOBAL % NBLOCK
IF (GLOBAL % AXSYM == 2) THEN
   GITDIM = 3
ELSE
   GITDIM = 2
END IF

ALLOCATE(BLOCKS(GLOBAL%NBLOCK))

IF (GLOBAL%DBG == 1) WRITE(*,'(4(A5,X))') "BLOCK","NCI","NCJ","CNK"

DO B = 1,GLOBAL % NBLOCK
   IF (GLOBAL % AXSYM == 2) THEN
      READ(GIT_UNIT) BLOCKS(B) % NPI, BLOCKS(B) % NPJ, BLOCKS(B) % NPK
      BLOCKS(B) % NCI = BLOCKS(B) % NPI - 1
      BLOCKS(B) % NCJ = BLOCKS(B) % NPJ - 1
      BLOCKS(B) % NCK = BLOCKS(B) % NPK - 1
   ELSE
      READ(GIT_UNIT) BLOCKS(B) % NPI, BLOCKS(B) % NPJ
      BLOCKS(B) % NPK = 1
      BLOCKS(B) % NCI = BLOCKS(B) % NPI - 1
      BLOCKS(B) % NCJ = BLOCKS(B) % NPJ - 1
      BLOCKS(B) % NCK = 1
   END IF

   IF (GLOBAL%DBG == 1) WRITE(*,'(4(I5,X))') B, BLOCKS(B) % NCI, BLOCKS(B) % NCJ, BLOCKS(B) % NCK

   ALLOCATE (BLOCKS(B) % XYZ(BLOCKS(B) % NPI, BLOCKS(B) % NPJ, BLOCKS(B) % NPK, 3))

END DO !B= 1,NB  SCHLEIFE ÜBER BLÖCKE GIT
DO B = 1,GLOBAL % NBLOCK
   DO k = 1,BLOCKS(B) %  NPK
      DO j = 1,BLOCKS(B) % NPJ
         DO i= 1,BLOCKS(B) % NPI
            READ(GIT_UNIT) (BLOCKS(B) % XYZ(I,J,K,V),v=1,GITDIM)
         END DO
      END DO
   END DO
END DO !B= 1,NB  SCHLEIFE ÜBER BLÖCKE GIT IN

WRITE(*,*)
WRITE(*,'("========== GIT_IN =========")')
IF(GLOBAL % AXSYM == 2) THEN
   WRITE(*,'("3D SIMULATION")')
ELSE IF (GLOBAL % AXSYM == 1) THEN
   WRITE(*,'("2D ROTATIONSYMETRISCHE SIMULATION")')
ELSE
   WRITE(*,'("2D SIMULATION")')
END IF
WRITE(*,'("BLOCKS ON FILE:         ",I0)') GLOBAL % NBLOCK

DO B = 1,GLOBAL % NBLOCK

END DO

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!              INITIALISIERUNGEN FÜR DIE BLOCK CONNECTIONS        !!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
IF (GLOBAL % AXSYM == 2) THEN
   NUMBER_OF_CORNER_POINTS = 8
   NUMBER_OF_FACES = 6
   NUMBER_OF_POINTS_PER_FACE = 4
   NUMBER_OF_PERMUTATIONS = 8
ELSE
   NUMBER_OF_CORNER_POINTS = 8
   NUMBER_OF_FACES = 4
   NUMBER_OF_POINTS_PER_FACE = 2
   NUMBER_OF_PERMUTATIONS = 2
END IF

ALLOCATE( CORNER_POINT (GLOBAL % NBLOCK,NUMBER_OF_CORNER_POINTS,GITDIM) )
ALLOCATE( FID2CP       (NUMBER_OF_FACES, NUMBER_OF_POINTS_PER_FACE))
ALLOCATE( PERM         (NUMBER_OF_PERMUTATIONS,NUMBER_OF_POINTS_PER_FACE))
IF (GLOBAL % AXSYM == 2) THEN

   FID2CP(1,1:NUMBER_OF_POINTS_PER_FACE)=(/1,3,5,7/)
   FID2CP(2,1:NUMBER_OF_POINTS_PER_FACE)=(/2,4,6,8/)
   FID2CP(3,1:NUMBER_OF_POINTS_PER_FACE)=(/1,2,5,6/)
   FID2CP(4,1:NUMBER_OF_POINTS_PER_FACE)=(/3,4,7,8/)
   FID2CP(5,1:NUMBER_OF_POINTS_PER_FACE)=(/1,2,3,4/)
   FID2CP(6,1:NUMBER_OF_POINTS_PER_FACE)=(/5,6,7,8/)

   PERM(1,1:NUMBER_OF_POINTS_PER_FACE)=(/1,2,3,4/)
   PERM(2,1:NUMBER_OF_POINTS_PER_FACE)=(/2,3,4,1/)
   PERM(3,1:NUMBER_OF_POINTS_PER_FACE)=(/3,4,1,2/)
   PERM(4,1:NUMBER_OF_POINTS_PER_FACE)=(/4,1,2,3/)
   PERM(5,1:NUMBER_OF_POINTS_PER_FACE)=(/4,3,2,1/)
   PERM(6,1:NUMBER_OF_POINTS_PER_FACE)=(/3,2,1,4/)
   PERM(7,1:NUMBER_OF_POINTS_PER_FACE)=(/2,1,4,3/)
   PERM(8,1:NUMBER_OF_POINTS_PER_FACE)=(/1,4,3,2/)

ELSE

   FID2CP(1,1:NUMBER_OF_POINTS_PER_FACE)=(/1,3/)
   FID2CP(2,1:NUMBER_OF_POINTS_PER_FACE)=(/2,4/)
   FID2CP(3,1:NUMBER_OF_POINTS_PER_FACE)=(/1,2/)
   FID2CP(4,1:NUMBER_OF_POINTS_PER_FACE)=(/3,4/)

   PERM(1,1:NUMBER_OF_POINTS_PER_FACE)=(/1,2/)
   PERM(2,1:NUMBER_OF_POINTS_PER_FACE)=(/2,1/)

END IF
!!!!!!!!! STORING CORNER POINTS
IF (GLOBAL % AXSYM == 2) THEN
   DO V = 1, GITDIM
      DO B = 1,GLOBAL % NBLOCK
         nI = BLOCKS(B) % NPI
         nJ = BLOCKS(B) % NPJ
         nK = BLOCKS(B) % NPK
         CORNER_POINT(B,1,V) = BLOCKS(B) % XYZ( 1, 1, 1, V)
         CORNER_POINT(B,2,V) = BLOCKS(B) % XYZ(ni, 1, 1, V)
         CORNER_POINT(B,3,V) = BLOCKS(B) % XYZ( 1,nj, 1, V)
         CORNER_POINT(B,4,V) = BLOCKS(B) % XYZ(ni,nj, 1, V)
         CORNER_POINT(B,5,V) = BLOCKS(B) % XYZ( 1, 1,nk, V)
         CORNER_POINT(B,6,V) = BLOCKS(B) % XYZ(ni, 1,nk, V)
         CORNER_POINT(B,7,V) = BLOCKS(B) % XYZ( 1,nj,nk, V)
         CORNER_POINT(B,8,V) = BLOCKS(B) % XYZ(ni,nj,nk, V)
      END DO
   END DO

ELSE
   DO V = 1, GITDIM
      DO B = 1,GLOBAL % NBLOCK
         nI = BLOCKS(B) % NPI
         nJ = BLOCKS(B) % NPJ
         CORNER_POINT(B,1,V) = BLOCKS(B) % XYZ( 1, 1, 1, V)
         CORNER_POINT(B,2,V) = BLOCKS(B) % XYZ(ni, 1, 1, V)
         CORNER_POINT(B,3,V) = BLOCKS(B) % XYZ( 1,nj, 1, V)
         CORNER_POINT(B,4,V) = BLOCKS(B) % XYZ(ni,nj, 1, V)
      END DO
   END DO
END IF

FOUND = .TRUE.
!WRITE(*,'(4(A5,X),6(A2,X))') "BLOCK","NCI","NCJ","NCK",FACES(1:NUMBER_OF_FACES)
DO B = 1,GLOBAL % NBLOCK  ! LOOP OVER ALL BLOCKS
!   WRITE(*,'(4(I5,X))',ADVANCE="NO") B, BLOCKS(B) % NCI, BLOCKS(B) % NCJ, BLOCKS(B) % NCK
   BLOCKS(B) % BLOCK_CONNECTION = -1
   DO F = 1, NUMBER_OF_FACES
      DO BB = 1,GLOBAL % NBLOCK! LOOP OVER ALL BLOCK AGAIN
         FOUND = .FALSE.
         IF (b == bb) CYCLE
         DO FF = 1,NUMBER_OF_FACES
            DO P = 1, NUMBER_OF_PERMUTATIONS
               FOUND = .TRUE.
               DO FP = 1, NUMBER_OF_POINTS_PER_FACE
                  DO V = 1, GITDIM
!                        WRITE(*,*) B,FID2CP(F,FP),V, BB,FID2CP(FF,PERM(P,FP)),V
!                        CORNER_POINT(B,FID2CP(F,FP),V)
                     IF (ABS(CORNER_POINT(B,FID2CP(F,FP),V) - CORNER_POINT(BB,FID2CP(FF,PERM(P,FP)),V)) > EPS) THEN
                        FOUND = .FALSE.
                        EXIT
                     END IF
                  END DO
                  IF (.NOT.FOUND) THEN
                     EXIT
                  END IF
               END DO
               IF (FOUND) THEN
                  BLOCKS(B) % BLOCK_CONNECTION(F,1) = BB
                  BLOCKS(B) % BLOCK_CONNECTION(F,2) = FF
                  BLOCKS(B) % BLOCK_CONNECTION(F,3) = P
                  EXIT
               END IF
            END DO
            IF (FOUND) THEN
               EXIT
            END IF
         END DO
         IF (FOUND) THEN

            EXIT


         END IF
      END DO
!      IF (FOUND) THEN
!         WRITE(*,'(I2,X)',ADVANCE="NO") BB
!      ELSE
!         WRITE(*,'(A2,X)',ADVANCE="NO") "--"
!      END IF
   END DO
   WRITE(*,*)
END DO


CLOSE(GIT_UNIT)
DEALLOCATE( CORNER_POINT)
DEALLOCATE( FID2CP )
DEALLOCATE( PERM)

END SUBROUTINE
