SUBROUTINE OUTPUT_GRID()
USE MOD_GLOBAL
USE CONST
IMPLICIT NONE
INTEGER, PARAMETER :: GIT_UNIT = 25


INTEGER :: GITDIM

INTEGER :: B,I,J,K,V


WRITE(*,'(2A,X,A)') "WRITEING ",TRIM(GLOBAL % GIT_OUT)

IF (GLOBAL % AXSYM == 2) THEN
   GITDIM = 3
ELSE
   GITDIM = 2
END IF

OPEN(GIT_UNIT,FILE=TRIM(GLOBAL% GIT_OUT),FORM="UNFORMATTED",access="STREAM",STATUS="replace")

WRITE(GIT_UNIT) GLOBAL %AXSYM,GLOBAL % NBLOCK

DO B = 1,GLOBAL % NBLOCK
   IF (GLOBAL % AXSYM == 2) THEN
      WRITE(GIT_UNIT) BLOCKS(B) % NPI, BLOCKS(B) % NPJ, BLOCKS(B) % NPK
   ELSE
      WRITE(GIT_UNIT) BLOCKS(B) % NPI, BLOCKS(B) % NPJ
   END IF

END DO !B= 1,NB  SCHLEIFE ÜBER BLÖCKE GIT

DO B = 1,GLOBAL % NBLOCK
   DO k = 1,BLOCKS(B) %  NPK
      DO j = 1,BLOCKS(B) % NPJ
         DO i= 1,BLOCKS(B) % NPI
            WRITE(GIT_UNIT) (BLOCKS(B) % XYZ(I,J,K,V),V=1,GITDIM)
         END DO
      END DO
   END DO
END DO !B= 1,NB  SCHLEIFE ÜBER BLÖCKE GIT IN

CLOSE(GIT_UNIT)


END SUBROUTINE
