SUBROUTINE UNSTR2STR
USE MOD_GLOBAL
IMPLICIT NONE

INTEGER :: N,I,J,K,UP,DIM

   WRITE(*,"(A)") "STRUKTURIERTES GITTER WIRD AUS DEN UNSTRUKTURIERTEN GITTER ERSTELLT"
IF (GLOBAL % AXSYM == 2) THEN
   WRITE(*,*) "3D NOCH NICHT UNTERSTÜTZT","unstr2str"
   STOP
END IF

DO N = 1,GLOBAL%NBLOCK
   DO I = 1,BLOCKS(N)%NPI
      DO J = 1,BLOCKS(N)%NPJ
         DO K = 1,BLOCKS(N)%NPK
            UP = BLOCKS(N) % ASSOC(I,J,K)
            DO DIM = 1,2
               BLOCKS(N) % XYZ(I,J,K,DIM) = UNSTR % XYZ(UP,DIM)
            END DO
            BLOCKS(N) % XYZ(I,J,K,3) = 0.0D0
         END DO
      END DO
   END DO
END DO

IF (GLOBAL%DBG >= 2)  THEN
   N = 1
   K = 1
   DO J = 1,BLOCKS(N)%NPJ
      DO I = 1,BLOCKS(N)%NPI
         WRITE(*,*) BLOCKS(N) % ASSOC(I,J,K),BLOCKS(N) % XYZ(I,J,K,:)
      END DO
   END DO
END IF


END SUBROUTINE
