program gridgen_nozzle_simple
implicit none

REAL(KIND = 8), PARAMETER :: POS_THROAT = 0.3

INTEGER, PARAMETER :: NI   = 20
INTEGER, PARAMETER :: NI_THROAT = NI * POS_THROAT

INTEGER, PARAMETER :: NJ = 10

INTEGER, PARAMETER :: FU = 666
INTEGER, PARAMETER :: NB = 1
INTEGER, PARAMETER :: AXSYM = 0

REAL(KIND = 8), PARAMETER :: Y_IN     = 2.0D0
REAL(KIND = 8), PARAMETER :: Y_THROAT = 1.0D0
REAL(KIND = 8), PARAMETER :: Y_END    = 3.0D0
REAL(KIND = 8), PARAMETER :: X_END    = 7.0D0
REAL(KIND = 8), PARAMETER :: X_THROAT = X_END * POS_THROAT

INTEGER :: I ,J
REAL(KIND = 8) :: spktx,spkty,epkty,epktx,lx,ly, y_max
WRITE(*,*) "GRIDGEN for a simple NOZZLE 29.01.2015"

WRITE(*,'(A,3(X,A,":",X,I0))') "GITTERDIMENSIONEN:", "NI",NI,"NI_THROAT",NI_THROAT,"NJ",NJ

WRITE(*,*) "INLET : Y:", Y_IN
WRITE(*,*) "THROAT: X:", X_THROAT,"Y:",Y_THROAT
WRITE(*,*) "EXIT  : X:", X_END   ,"Y:",Y_END
OPEN(FU,FILE="git.bin",FORM="UNFORMATTED",access="STREAM",STATUS="replace")

WRITE(FU) AXSYM,NB

!!! BLOCK 1.
WRITE(FU) NI+1,NJ+1
!!! BLOCK 2.

DO J = 0, NJ
   DO I = 0,NI
      IF (I < NI_THROAT) then
         Y_MAX = Y_IN - (Y_IN - Y_THROAT) * DBLE(I) / DBLE(NI_THROAT)

      else
         Y_MAX = Y_THROAT + (Y_END-Y_THROAT) * DBLE(I-NI_THROAT) / DBLE(NI-NI_THROAT)
      end if
      WRITE(FU) X_END * DBLE(I)/DBLE(NI), Y_MAX * DBLE(J)/DBLE(NJ)
   END DO
END DO

CLOSE(FU)
WRITE(*,*) "DONE"


end program gridgen_nozzle_simple
