program gridgen_o_grid
implicit none
INTEGER, PARAMETER :: NB = 1
INTEGER, PARAMETER :: AXSYM = 0
INTEGER, PARAMETER :: NI = 12
INTEGER, PARAMETER :: NJ = 2
INTEGER, PARAMETER :: FU = 666

INTEGER :: I ,J
WRITE(*,*) "GRIDGEN FÜR EIN EINFACHES 1D GITTER 28.01.2015"

OPEN(FU,FILE="git.bin",FORM="UNFORMATTED",access="STREAM",STATUS="replace")

WRITE(FU) AXSYM,NB
!!! BLOCK 1.
WRITE(FU) NI+1,NJ+1

DO J = 0, NJ
   DO I = 0,NI
!      WRITE(FU) (DBLE(I)/DBLE(NI)),(DBLE(J)/DBLE(NJ))
      WRITE(FU) SQRT((DBLE(I)/DBLE(NI))),(DBLE(J)/DBLE(NJ))**2
   END DO
END DO


CLOSE (FU)
WRITE(*,*) "DONE"


end program
